### ISSUE TITLE
surplus arm64-v8a in build.sh.

### ISSUE THREAD

**Issue by yuanlida** [dinhviethoa/ctemplate#1]
# Start building.
ANDROID_PLATFORM=android-16
archs="armeabi armeabi-v7a x86 **arm64-v8a**"
for arch in $archs ; do
  TARGET_ARCH_ABI=$arch
  build
done
ANDROID_PLATFORM=android-21
archs="arm64-v8a"
for arch in $archs ; do
  TARGET_ARCH_ABI=$arch
  build
done

**Comment by dinhvh** [comment]
Fixed with 2c37d13940c555abb7eb9932a5ab428a99ff6db4
